backend:
  name: git-gateway
  branch: main # Change to your production branch

local_backend: true # Enables Netlify CMS locally

publish_mode: editorial_workflow # Adds more options to content management

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true # Displays a preview of your post while editing it
      fields: # Fields get placed in resulting Markdown file
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Publish Date', name: 'date', widget: 'datetime' }
        - { label: 'Description', name: 'description', widget: 'string' }
        - { label: 'Body', name: 'body', widget: 'markdown' }